### ISSUE TITLE
let the item run out

### ISSUE THREAD

**Issue by KaTulib** [Flooflez/ChexmixMod#1]
I love this mod so much It would mean the world to me if the chex mix wasn't completely infinite though so my server can have a balanced diet (get it? haha, food humor)
((for 1.19.2 would be very nice too :) ))

**Comment by Flooflez** [comment]
yeah sure I can probably do that, what version of Minecraft do you play on?

**Comment by Flooflez** [comment]
Yeah sure, do you want me to update it for all versions or just for 1.19.2?

**Comment by KaTulib** [comment]
1.19.2 works best for me but if you wanna do all versions that may make many people happy

**Comment by Flooflez** [comment]
ok done, it should be published to Modrinth now live. I'll get Curseforge downloads working tmr. 
download here: https://modrinth.com/mod/chex-mix-mod/versions

I didn't have much time to test so let me know if there are any bugs/issue that you find.
I'm going to close this issue now, happy snackin' :)
